# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
from pathlib import Path
# sys.path.insert(0, os.path.abspath('../src/WPSProtocol'))

# parent = Path(conf.py).parent
# sys.paths = Path(confy.py).parents[1]

# try:
#   import WPSProtocol
# except ImportError:
#   print("oh no 1")

sys.path.insert(0, os.path.abspath(os.path.join("..", "..", "src"))) # Works on local systems



# -- Project information -----------------------------------------------------

project = 'WalshPulSeqProtocol'
copyright = '2024, Jessica John Britto'
author = 'Jessica John Britto'

# The full version, including alpha/beta/rc tags
release = '1.0.post4'


# import mock

# MOCK_MODULES = ['numpy', 'scipy', 'sklearn', 'matplotlib', 'matplotlib.pyplot', 'scipy.interpolate', 'scipy.special', 'math', '__future__', 'toolboxutilities']
# for mod_name in MOCK_MODULES:
#     sys.modules[mod_name] = mock.Mock()


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo',            # Support for TODO notes
    # 'sphinx.ext.napoleon',        # Supports Google and NumPy style docstrings
    'sphinx.ext.viewcode',        # Add links to highlighted source code
    'sphinx.ext.autodoc',         # Automatically document from docstrings
    # 'sphinx.ext.intersphinx',     # Link to other project’s documentation
    # 'sphinx.ext.mathjax',         # For rendering LaTeX-style math
    # 'sphinx.ext.githubpages',
    # "sphinx_wagtail_theme",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'English'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    '_build',           # Directory where the output files are generated
    'Thumbs.db',        # Windows thumbnail cache files
    '.DS_Store',        # macOS directory metadata files
    # 'venv',             # Virtual environment directory (if present)
    # 'env',              # Alternative name for a virtual environment
    # 'docs/modules.rst', # If you want to exclude a specific file like modules.rst
    '**.ipynb_checkpoints',  # Jupyter notebook checkpoints
    '*.egg-info',       # Metadata for Python packages
    # 'build',            # General build directory (if present)
    # '.tox',             # Test environments (like tox directories)
]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'
# html_theme = 'sphinx_wagtail_theme'
# html_logo = "_static/custom_logo.png"
# html_title = "My Custom Documentation"
# html_theme_options = { 'logo_only': False, }
# html_logo = '_static/block2-logo-white.png'
html_logo = ""
html_title = "WalshPulseSeqProtocol"

html_theme_options = {
    "footer_icons": [
        {
            "name": "GitHub",
            "url": "https://github.com/JessicaJohnBritto",
            "html": """
                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
                </svg>
            """,
            "class": "",
        },
    ],
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']